### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by theMillenniumFalcon** [akaditya394/medassist#50]
These tasks are ordered on the basis of priority:

- [ ] Implement state management in we app
- [ ] Make all stuff work in web app with server
- [ ] Finalize the data set, and write the jupyter notebook
- [ ] Deploy to cloud, server and jupyter notebook
- [ ] Add Open AI integration
- [ ] Change design of app
- [ ] Change design of PPT
